name: simple_shadow
description: A customizable shadow for any widget
version: 0.1.0
author: Marcelo P. Montanher
homepage: https://github.com/marcelopmont/simple_shadow.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: